name: bloco_personalizavel
description: Bloco de notas offline com temas e fontes personalizaveis.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/wallpapers/
    - assets/app_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf

flutter_launcher_icons:
  android: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#381074"
  adaptive_icon_foreground: assets/app_icon.png
